# Generated by Django 2.2.6 on 2021-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstore',
            name='reciTeam',
            field=models.CharField(default=1, max_length=128, verbose_name='自用/班组'),
            preserve_default=False,
        ),
    ]
