# Generated by Django 2.2.6 on 2020-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=128, verbose_name='材料类别')),
                ('mclass', models.CharField(max_length=128, verbose_name='材料小类')),
                ('content', models.TextField(blank=True, max_length=256, null=True, verbose_name='核算内容')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'mclass',
                'ordering': ['-create_time'],
            },
        ),
    ]
